"""LLM-as-judge check for AI-generated code that's been cleaned of the
literal chat-leakage artifacts leakage_scan.py catches. This is
fundamentally a judgment call, not a fact — unlike leakage_scan, there is
no textual fingerprint to point at once someone edits AI output, so this
requires an actual model reading the code for style, not a regex matching
it. Explicitly advisory, explicitly lower-confidence than leakage_scan:
false positives are accepted here (a careful, thorough human can still read
as "AI-like"), so this must never be treated as fact the way leakage_scan's
findings are — keep the two clearly separate rather than merging them."""
import json
import re
from pathlib import Path

from app.services.llm.base import Message
from app.services.llm.factory import get_llm_client

MAX_FILE_CHARS = 20_000
MAX_TOTAL_CHARS = 120_000

_TEXT_EXTENSIONS = {
    ".md", ".txt", ".json", ".toml", ".yaml", ".yml", ".py", ".sh", ".pl",
    ".csv", ".cfg", ".ini", ".rego",
    ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
    ".c", ".h", ".cpp", ".cc", ".cxx", ".hpp",
    ".java", ".go", ".rb", ".rs", ".sql",
}
_TEXT_FILENAMES = {"Makefile", "makefile", "Dockerfile", "dockerfile"}

SYSTEM_PROMPT = """You are reviewing a submitted task's SOLUTION CODE for signs it was generated by \
an LLM in one pass and submitted with little or no human iteration — as opposed to code a human \
wrote and edited while actually solving the problem.

There is no reliable fingerprint for this — you are making a judgment call, and false positives \
are expected and acceptable. A careful, thorough human can legitimately read as "AI-like." Do not \
overstate your confidence. Ground every claim in a specific, quotable piece of evidence from the \
actual code you were given — never a vague impression.

Look specifically for:
1. Uniform polish with no trace of iteration — no leftover debug prints, no commented-out old \
attempts, no rough edges anywhere. Real iterative human work usually has at least one.
2. Comments that explain WHAT the code does rather than WHY (e.g. "// increment counter" above \
`counter++`) — humans don't narrate the obvious about their own code; this is a default LLM habit.
3. Edge-case handling that goes well beyond what the task's actual described scope calls for.
4. Docstring/comment density that's suspiciously uniform across every function regardless of how \
trivial or complex each one is.
5. Phrasing echoes between instruction.md and the solution's own comments — shared unusual word \
choices or sentence structure suggesting both were generated in the same pass rather than a human \
reading instructions and separately writing code.

Respond with ONLY a JSON object, no other text, in exactly this shape:
{
  "likely_ai_generated": true or false,
  "confidence": "low" or "medium" or "high",
  "reasoning": ["specific, quotable observation 1", "specific, quotable observation 2", ...]
}
If you don't find convincing evidence for any signal, set likely_ai_generated to false and explain \
why the code reads as human-iterated instead. Never claim high confidence without at least two \
distinct, concrete pieces of evidence."""


def _read_text_files(root: Path, max_total: int = MAX_TOTAL_CHARS) -> str:
    chunks: list[str] = []
    total = 0
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() not in _TEXT_EXTENSIONS and path.name not in _TEXT_FILENAMES:
            continue
        try:
            content = path.read_text(errors="replace")
        except OSError:
            continue
        if len(content) > MAX_FILE_CHARS:
            content = content[:MAX_FILE_CHARS] + "\n... [truncated]"
        rel = path.relative_to(root)
        chunk = f"--- {rel} ---\n{content}\n"
        if total + len(chunk) > max_total:
            chunks.append("... [remaining files omitted, budget reached]")
            break
        chunks.append(chunk)
        total += len(chunk)
    return "\n".join(chunks)


def _parse_verdict(text: str) -> dict:
    stripped = text.strip()
    match = re.search(r"\{.*\}", stripped, re.DOTALL)
    if match:
        stripped = match.group(0)
    try:
        data = json.loads(stripped)
    except (json.JSONDecodeError, ValueError):
        return {
            "likely_ai_generated": False,
            "confidence": "low",
            "reasoning": [f"Judge response was not valid JSON; treating as inconclusive: {text[:2000]}"],
        }
    return {
        "likely_ai_generated": bool(data.get("likely_ai_generated", False)),
        "confidence": str(data.get("confidence", "low")),
        "reasoning": [str(r) for r in data.get("reasoning", [])] if isinstance(data.get("reasoning"), list) else [],
    }


async def run_code_smell_judge(task_root: Path) -> dict:
    instruction_path = task_root / "instruction.md"
    solution_dir = task_root / "solution"
    environment_dir = task_root / "environment"

    instruction_text = instruction_path.read_text(errors="replace") if instruction_path.is_file() else ""
    solution_text = _read_text_files(solution_dir) if solution_dir.is_dir() else ""
    environment_text = _read_text_files(environment_dir) if environment_dir.is_dir() else ""

    user_content = (
        "=== instruction.md ===\n"
        f"{instruction_text}\n\n"
        "=== solution/ ===\n"
        f"{solution_text or '(empty or missing)'}\n\n"
        "=== environment/ ===\n"
        f"{environment_text or '(empty or missing)'}\n"
    )

    client = get_llm_client()
    response = await client.complete(
        [
            Message(role="system", content=SYSTEM_PROMPT),
            Message(role="user", content=user_content),
        ],
        tools=[],
    )
    return _parse_verdict(response.text)
